---
site_name: Augmented Living using Kubernetes
site_url: http://localhost:8002
site_author: D. Brian Kimmel
dev_addr: 127.0.0.1:8002

theme:
    name: material
    palette:
        primary: light blue

extra_css:
    - stylesheets/extra.css

extra_javascript:
    - javascripts/extra.js

#plugins:
#    - git-revision-date

nav:
    - Home: index.md
    - License: license.md
    - About: about.md

markdown_extensions:
    - attr_list